name: AWS-Infra Create

on:
  workflow_dispatch:

jobs:
  setup-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform for Backend
        run: terraform init
        working-directory: ./setup-backend

      - name: Apply Terraform to create Backend
        run: terraform apply -auto-approve
        working-directory: ./setup-backend

      - name: Export S3 Bucket Name
        run: |
          terraform output -raw bucket_name > bucket_name.txt
          echo "S3_BUCKET_NAME=$(cat bucket_name.txt)" >> $GITHUB_ENV
        working-directory: ./setup-backend

  terraform:
    needs: setup-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform with Backend Configuration
        env:
          S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET_NAME }}" -backend-config="key=terraform-state-file/statefile" -backend-config="region=us-west-2"
        working-directory: ./main

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./main

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./main
